'''
Copyright (c) 2008-2020 Citrix Systems, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
'''


from massrc.com.citrix.mas.nitro.resource.Base import *
from massrc.com.citrix.mas.nitro.service.options import options
from massrc.com.citrix.mas.nitro.exception.nitro_exception import nitro_exception
from massrc.com.citrix.mas.nitro.util.filtervalue import filtervalue
from massrc.com.citrix.mas.nitro.resource.Base.base_resource import base_resource
from massrc.com.citrix.mas.nitro.resource.Base.base_response import base_response
from massrc.com.citrix.mas.nitro.resource.config.mps.app_component import app_component


'''
Configuration for Applications Managed by Management System resource
'''

class application(base_resource):
	_throughput_avg= ""
	_vsvc_port_criteria= ""
	_app_type= ""
	_ns_ip_address= ""
	_configpack_id= ""
	_application_class= ""
	_family= ""
	_vsvr_name_criteria= ""
	_id= ""
	_cursrvrconnections= ""
	_name= ""
	_svr_name_criteria= ""
	_svr_ip_address_criteria= ""
	_curclntconnections= ""
	_user_name_enc= ""
	_tenant_id= ""
	_user_name= ""
	_application_managed= ""
	_app_category= ""
	_vsvr_ip_address_criteria= ""
	_tags= ""
	_svc_port_criteria= ""
	_tenant_name= ""
	_no_of_gslbsvc= ""
	_stylebook_params= ""
	_no_of_svcgrp= ""
	_no_of_svr= ""
	_no_of_gslb= ""
	_no_of_auth= ""
	_app_name_references_array=[]
	_application_ids=[]
	_no_of_svc= ""
	_act_id= ""
	_app_info_required= ""
	_no_of_vpn= ""
	_no_of_lb= ""
	_no_of_cs= ""
	_vsvr_app_components=[]
	_is_migration= ""
	_force_delete= ""
	_no_of_cr= ""
	__count=""
	'''
	get the resource id
	'''
	def get_resource_id(self) :
		try:
			if hasattr(self, 'id'):
				return self.id 
			else:
				return None 
		except Exception as e :
			raise e

	'''
	get the resource type
	'''
	def get_object_type(self) :
		try:
			return "application"
		except Exception as e :
			raise e

	'''
	Returns the value of object identifier argument.
	'''
	def get_object_id(self) :
		try:
			return self._id
		except Exception as e :
			raise e

	'''
	Returns the value of object file path argument.
	'''
	@property
	def file_path_value(self) :
		try:
			return None
		except Exception as e :
			raise e

	'''
	Returns the value of object file component name.
	'''
	@property
	def file_component_value(self) :
		try :
			return "applications"
		except Exception as e :
			raise e



	'''
	get Sum of throughput across all vips of the app
	'''
	@property
	def throughput_avg(self) :
		try:
			return self._throughput_avg
		except Exception as e :
			raise e
	'''
	set Sum of throughput across all vips of the app
	'''
	@throughput_avg.setter
	def throughput_avg(self,throughput_avg):
		try :
			if not isinstance(throughput_avg,float):
				raise TypeError("throughput_avg must be set to float value")
			self._throughput_avg = throughput_avg
		except Exception as e :
			raise e


	'''
	get vsvc_port_criteria
	'''
	@property
	def vsvc_port_criteria(self) :
		try:
			return self._vsvc_port_criteria
		except Exception as e :
			raise e
	'''
	set vsvc_port_criteria
	'''
	@vsvc_port_criteria.setter
	def vsvc_port_criteria(self,vsvc_port_criteria):
		try :
			if not isinstance(vsvc_port_criteria,str):
				raise TypeError("vsvc_port_criteria must be set to str value")
			self._vsvc_port_criteria = vsvc_port_criteria
		except Exception as e :
			raise e


	'''
	get Application Type - 0: HMCUserDefined, 1: HMCAutoGenerated, 2: CNN App
	'''
	@property
	def app_type(self) :
		try:
			return self._app_type
		except Exception as e :
			raise e
	'''
	set Application Type - 0: HMCUserDefined, 1: HMCAutoGenerated, 2: CNN App
	'''
	@app_type.setter
	def app_type(self,app_type):
		try :
			if not isinstance(app_type,int):
				raise TypeError("app_type must be set to int value")
			self._app_type = app_type
		except Exception as e :
			raise e


	'''
	get ns_ip_address
	'''
	@property
	def ns_ip_address(self) :
		try:
			return self._ns_ip_address
		except Exception as e :
			raise e
	'''
	set ns_ip_address
	'''
	@ns_ip_address.setter
	def ns_ip_address(self,ns_ip_address):
		try :
			if not isinstance(ns_ip_address,str):
				raise TypeError("ns_ip_address must be set to str value")
			self._ns_ip_address = ns_ip_address
		except Exception as e :
			raise e


	'''
	get Config pack Id.
	'''
	@property
	def configpack_id(self) :
		try:
			return self._configpack_id
		except Exception as e :
			raise e
	'''
	set Config pack Id.
	'''
	@configpack_id.setter
	def configpack_id(self,configpack_id):
		try :
			if not isinstance(configpack_id,str):
				raise TypeError("configpack_id must be set to str value")
			self._configpack_id = configpack_id
		except Exception as e :
			raise e


	'''
	get Application class
	'''
	@property
	def application_class(self) :
		try:
			return self._application_class
		except Exception as e :
			raise e


	'''
	get Application Family
	'''
	@property
	def family(self) :
		try:
			return self._family
		except Exception as e :
			raise e
	'''
	set Application Family
	'''
	@family.setter
	def family(self,family):
		try :
			if not isinstance(family,str):
				raise TypeError("family must be set to str value")
			self._family = family
		except Exception as e :
			raise e


	'''
	get vsvr_name_criteria
	'''
	@property
	def vsvr_name_criteria(self) :
		try:
			return self._vsvr_name_criteria
		except Exception as e :
			raise e
	'''
	set vsvr_name_criteria
	'''
	@vsvr_name_criteria.setter
	def vsvr_name_criteria(self,vsvr_name_criteria):
		try :
			if not isinstance(vsvr_name_criteria,str):
				raise TypeError("vsvr_name_criteria must be set to str value")
			self._vsvr_name_criteria = vsvr_name_criteria
		except Exception as e :
			raise e


	'''
	get Id is system generated key.
	'''
	@property
	def id(self) :
		try:
			return self._id
		except Exception as e :
			raise e


	'''
	get cursrvrconnections Value across all vips of the app
	'''
	@property
	def cursrvrconnections(self) :
		try:
			return self._cursrvrconnections
		except Exception as e :
			raise e
	'''
	set cursrvrconnections Value across all vips of the app
	'''
	@cursrvrconnections.setter
	def cursrvrconnections(self,cursrvrconnections):
		try :
			if not isinstance(cursrvrconnections,float):
				raise TypeError("cursrvrconnections must be set to float value")
			self._cursrvrconnections = cursrvrconnections
		except Exception as e :
			raise e


	'''
	get Application Name
	'''
	@property
	def name(self) :
		try:
			return self._name
		except Exception as e :
			raise e
	'''
	set Application Name
	'''
	@name.setter
	def name(self,name):
		try :
			if not isinstance(name,str):
				raise TypeError("name must be set to str value")
			self._name = name
		except Exception as e :
			raise e


	'''
	get svr_name_criteria
	'''
	@property
	def svr_name_criteria(self) :
		try:
			return self._svr_name_criteria
		except Exception as e :
			raise e
	'''
	set svr_name_criteria
	'''
	@svr_name_criteria.setter
	def svr_name_criteria(self,svr_name_criteria):
		try :
			if not isinstance(svr_name_criteria,str):
				raise TypeError("svr_name_criteria must be set to str value")
			self._svr_name_criteria = svr_name_criteria
		except Exception as e :
			raise e


	'''
	get svr_ip_address_criteria
	'''
	@property
	def svr_ip_address_criteria(self) :
		try:
			return self._svr_ip_address_criteria
		except Exception as e :
			raise e
	'''
	set svr_ip_address_criteria
	'''
	@svr_ip_address_criteria.setter
	def svr_ip_address_criteria(self,svr_ip_address_criteria):
		try :
			if not isinstance(svr_ip_address_criteria,str):
				raise TypeError("svr_ip_address_criteria must be set to str value")
			self._svr_ip_address_criteria = svr_ip_address_criteria
		except Exception as e :
			raise e


	'''
	get curclntconnections Value across all vips of the app
	'''
	@property
	def curclntconnections(self) :
		try:
			return self._curclntconnections
		except Exception as e :
			raise e
	'''
	set curclntconnections Value across all vips of the app
	'''
	@curclntconnections.setter
	def curclntconnections(self,curclntconnections):
		try :
			if not isinstance(curclntconnections,float):
				raise TypeError("curclntconnections must be set to float value")
			self._curclntconnections = curclntconnections
		except Exception as e :
			raise e


	'''
	get User Name
	'''
	@property
	def user_name_enc(self) :
		try:
			return self._user_name_enc
		except Exception as e :
			raise e


	'''
	get Tenant Id
	'''
	@property
	def tenant_id(self) :
		try:
			return self._tenant_id
		except Exception as e :
			raise e


	'''
	get User Name
	'''
	@property
	def user_name(self) :
		try:
			return self._user_name
		except Exception as e :
			raise e


	'''
	get Managed field
	'''
	@property
	def application_managed(self) :
		try:
			return self._application_managed
		except Exception as e :
			raise e
	'''
	set Managed field
	'''
	@application_managed.setter
	def application_managed(self,application_managed):
		try :
			if not isinstance(application_managed,bool):
				raise TypeError("application_managed must be set to bool value")
			self._application_managed = application_managed
		except Exception as e :
			raise e


	'''
	get Application Category
	'''
	@property
	def app_category(self) :
		try:
			return self._app_category
		except Exception as e :
			raise e
	'''
	set Application Category
	'''
	@app_category.setter
	def app_category(self,app_category):
		try :
			if not isinstance(app_category,str):
				raise TypeError("app_category must be set to str value")
			self._app_category = app_category
		except Exception as e :
			raise e


	'''
	get vsvr_ip_address_criteria
	'''
	@property
	def vsvr_ip_address_criteria(self) :
		try:
			return self._vsvr_ip_address_criteria
		except Exception as e :
			raise e
	'''
	set vsvr_ip_address_criteria
	'''
	@vsvr_ip_address_criteria.setter
	def vsvr_ip_address_criteria(self,vsvr_ip_address_criteria):
		try :
			if not isinstance(vsvr_ip_address_criteria,str):
				raise TypeError("vsvr_ip_address_criteria must be set to str value")
			self._vsvr_ip_address_criteria = vsvr_ip_address_criteria
		except Exception as e :
			raise e


	'''
	get Tags associated with application
	'''
	@property
	def tags(self) :
		try:
			return self._tags
		except Exception as e :
			raise e
	'''
	set Tags associated with application
	'''
	@tags.setter
	def tags(self,tags):
		try :
			if not isinstance(tags,str):
				raise TypeError("tags must be set to str value")
			self._tags = tags
		except Exception as e :
			raise e


	'''
	get svc_port_criteria
	'''
	@property
	def svc_port_criteria(self) :
		try:
			return self._svc_port_criteria
		except Exception as e :
			raise e
	'''
	set svc_port_criteria
	'''
	@svc_port_criteria.setter
	def svc_port_criteria(self,svc_port_criteria):
		try :
			if not isinstance(svc_port_criteria,str):
				raise TypeError("svc_port_criteria must be set to str value")
			self._svc_port_criteria = svc_port_criteria
		except Exception as e :
			raise e


	'''
	get Tenant Name
	'''
	@property
	def tenant_name(self) :
		try:
			return self._tenant_name
		except Exception as e :
			raise e

	'''
	Number of LB VIPs
	'''
	@property
	def no_of_gslbsvc(self):
		try:
			return self._no_of_gslbsvc
		except Exception as e :
			raise e
	'''
	Number of LB VIPs
	'''
	@no_of_gslbsvc.setter
	def no_of_gslbsvc(self,no_of_gslbsvc):
		try :
			if not isinstance(no_of_gslbsvc,str):
				raise TypeError("no_of_gslbsvc must be set to str value")
			self._no_of_gslbsvc = no_of_gslbsvc
		except Exception as e :
			raise e

	'''
	Stylebook Parameter
	'''
	@property
	def stylebook_params(self):
		try:
			return self._stylebook_params
		except Exception as e :
			raise e
	'''
	Stylebook Parameter
	'''
	@stylebook_params.setter
	def stylebook_params(self,stylebook_params):
		try :
			if not isinstance(stylebook_params,str):
				raise TypeError("stylebook_params must be set to str value")
			self._stylebook_params = stylebook_params
		except Exception as e :
			raise e

	'''
	Number of Service Groups
	'''
	@property
	def no_of_svcgrp(self):
		try:
			return self._no_of_svcgrp
		except Exception as e :
			raise e
	'''
	Number of Service Groups
	'''
	@no_of_svcgrp.setter
	def no_of_svcgrp(self,no_of_svcgrp):
		try :
			if not isinstance(no_of_svcgrp,str):
				raise TypeError("no_of_svcgrp must be set to str value")
			self._no_of_svcgrp = no_of_svcgrp
		except Exception as e :
			raise e

	'''
	Number of Servers
	'''
	@property
	def no_of_svr(self):
		try:
			return self._no_of_svr
		except Exception as e :
			raise e
	'''
	Number of Servers
	'''
	@no_of_svr.setter
	def no_of_svr(self,no_of_svr):
		try :
			if not isinstance(no_of_svr,str):
				raise TypeError("no_of_svr must be set to str value")
			self._no_of_svr = no_of_svr
		except Exception as e :
			raise e

	'''
	Number of GSLB VIPs
	'''
	@property
	def no_of_gslb(self):
		try:
			return self._no_of_gslb
		except Exception as e :
			raise e
	'''
	Number of GSLB VIPs
	'''
	@no_of_gslb.setter
	def no_of_gslb(self,no_of_gslb):
		try :
			if not isinstance(no_of_gslb,str):
				raise TypeError("no_of_gslb must be set to str value")
			self._no_of_gslb = no_of_gslb
		except Exception as e :
			raise e

	'''
	Number of AUTH VIPs
	'''
	@property
	def no_of_auth(self):
		try:
			return self._no_of_auth
		except Exception as e :
			raise e
	'''
	Number of AUTH VIPs
	'''
	@no_of_auth.setter
	def no_of_auth(self,no_of_auth):
		try :
			if not isinstance(no_of_auth,str):
				raise TypeError("no_of_auth must be set to str value")
			self._no_of_auth = no_of_auth
		except Exception as e :
			raise e

	'''
	All application names separated by comma that are referenced by this custom application
	'''
	@property
	def app_name_references_array(self) :
		try:
			return self._app_name_references_array
		except Exception as e :
			raise e
	'''
	All application names separated by comma that are referenced by this custom application
	'''
	@app_name_references_array.setter
	def app_name_references_array(self,app_name_references_array) :
		try :
			if not isinstance(app_name_references_array,list):
				raise TypeError("app_name_references_array must be set to array of str value")
			for item in app_name_references_array :
				if not isinstance(item,str):
					raise TypeError("item must be set to str value")
			self._app_name_references_array = app_name_references_array
		except Exception as e :
			raise e

	'''
	Application IDs that are part of this application
	'''
	@property
	def application_ids(self) :
		try:
			return self._application_ids
		except Exception as e :
			raise e
	'''
	Application IDs that are part of this application
	'''
	@application_ids.setter
	def application_ids(self,application_ids) :
		try :
			if not isinstance(application_ids,list):
				raise TypeError("application_ids must be set to array of str value")
			for item in application_ids :
				if not isinstance(item,str):
					raise TypeError("item must be set to str value")
			self._application_ids = application_ids
		except Exception as e :
			raise e

	'''
	Number of Services
	'''
	@property
	def no_of_svc(self):
		try:
			return self._no_of_svc
		except Exception as e :
			raise e
	'''
	Number of Services
	'''
	@no_of_svc.setter
	def no_of_svc(self,no_of_svc):
		try :
			if not isinstance(no_of_svc,str):
				raise TypeError("no_of_svc must be set to str value")
			self._no_of_svc = no_of_svc
		except Exception as e :
			raise e

	'''
	Activity Id
	'''
	@property
	def act_id(self):
		try:
			return self._act_id
		except Exception as e :
			raise e

	'''
	app_info_required
	'''
	@property
	def app_info_required(self):
		try:
			return self._app_info_required
		except Exception as e :
			raise e
	'''
	app_info_required
	'''
	@app_info_required.setter
	def app_info_required(self,app_info_required):
		try :
			if not isinstance(app_info_required,bool):
				raise TypeError("app_info_required must be set to bool value")
			self._app_info_required = app_info_required
		except Exception as e :
			raise e

	'''
	Number of VPN VIPs
	'''
	@property
	def no_of_vpn(self):
		try:
			return self._no_of_vpn
		except Exception as e :
			raise e
	'''
	Number of VPN VIPs
	'''
	@no_of_vpn.setter
	def no_of_vpn(self,no_of_vpn):
		try :
			if not isinstance(no_of_vpn,str):
				raise TypeError("no_of_vpn must be set to str value")
			self._no_of_vpn = no_of_vpn
		except Exception as e :
			raise e

	'''
	Number of LB VIPs
	'''
	@property
	def no_of_lb(self):
		try:
			return self._no_of_lb
		except Exception as e :
			raise e
	'''
	Number of LB VIPs
	'''
	@no_of_lb.setter
	def no_of_lb(self,no_of_lb):
		try :
			if not isinstance(no_of_lb,str):
				raise TypeError("no_of_lb must be set to str value")
			self._no_of_lb = no_of_lb
		except Exception as e :
			raise e

	'''
	Number of CS VIPs
	'''
	@property
	def no_of_cs(self):
		try:
			return self._no_of_cs
		except Exception as e :
			raise e
	'''
	Number of CS VIPs
	'''
	@no_of_cs.setter
	def no_of_cs(self,no_of_cs):
		try :
			if not isinstance(no_of_cs,str):
				raise TypeError("no_of_cs must be set to str value")
			self._no_of_cs = no_of_cs
		except Exception as e :
			raise e

	'''
	Application components
	'''
	@property
	def vsvr_app_components(self) :
		try:
			return self._vsvr_app_components
		except Exception as e :
			raise e
	'''
	Application components
	'''
	@vsvr_app_components.setter
	def vsvr_app_components(self,vsvr_app_components) :
		try :
			if not isinstance(vsvr_app_components,list):
				raise TypeError("vsvr_app_components must be set to array of app_component value")
			for item in vsvr_app_components :
				if not isinstance(item,app_component):
					raise TypeError("item must be set to app_component value")
			self._vsvr_app_components = vsvr_app_components
		except Exception as e :
			raise e

	'''
	is_migration
	'''
	@property
	def is_migration(self):
		try:
			return self._is_migration
		except Exception as e :
			raise e
	'''
	is_migration
	'''
	@is_migration.setter
	def is_migration(self,is_migration):
		try :
			if not isinstance(is_migration,bool):
				raise TypeError("is_migration must be set to bool value")
			self._is_migration = is_migration
		except Exception as e :
			raise e

	'''
	force delete
	'''
	@property
	def force_delete(self):
		try:
			return self._force_delete
		except Exception as e :
			raise e
	'''
	force delete
	'''
	@force_delete.setter
	def force_delete(self,force_delete):
		try :
			if not isinstance(force_delete,bool):
				raise TypeError("force_delete must be set to bool value")
			self._force_delete = force_delete
		except Exception as e :
			raise e

	'''
	Number of CR VIPs
	'''
	@property
	def no_of_cr(self):
		try:
			return self._no_of_cr
		except Exception as e :
			raise e
	'''
	Number of CR VIPs
	'''
	@no_of_cr.setter
	def no_of_cr(self,no_of_cr):
		try :
			if not isinstance(no_of_cr,str):
				raise TypeError("no_of_cr must be set to str value")
			self._no_of_cr = no_of_cr
		except Exception as e :
			raise e

	'''
	Use this operation to add application.
	'''
	@classmethod
	def add(cls,service=None,resource=None):
		try:
			cls._op_by_primary_key_name = ""
			cls._url_filter = ""
			if resource is None :
				raise Exception("Resource Object Not Found")
			if type(resource) is not list :
				res = resource.perform_operation(service)
				return res
			else : 
				application_obj= application()
				return cls.perform_operation_bulk_request(service,resource,application_obj)
		except Exception as e :
			raise e

	'''
	Use this operation to get application.
	'''
	@classmethod
	def get(cls,client = None,resource="",option_=""): 
		try:
			cls._op_by_primary_key_name = ""
			response=""
			if not resource :
				application_obj=application()
				response = application_obj.get_resources(client,option_)
			else:
				response = resource.get_resource(client, option_)
			return response
		except Exception as e :
			raise e

	'''
	Use this operation to modify application.
	'''
	@classmethod
	def update(cls,client=None,resource=None):
		try:
			cls._op_by_primary_key_name = ""
			cls._url_filter = ""
			if resource is None :
				raise Exception("Resource Object Not Found")
			if type(resource) is not list :
				res = resource.update_resource(client)
				return res
			else :
				application_obj=application()
				return cls.update_bulk_request(client,resource,application_obj)
		except Exception as e :
			raise e

	'''
	Use this operation to delete application.
	'''
	@classmethod
	def delete(cls,client=None,resource=None): 
		try :
			cls._op_by_primary_key_name = ""
			cls._url_filter = ""
			if resource is None :
				raise Exception("Resource Object Not Found")
			if type(resource) is not list :
				res = resource.delete_resource(client)
				return res
			else :
					application_obj=application()
					return cls.delete_bulk_request(client,resource,application_obj)
		except Exception as e :
			raise e

	'''
	Use this API to fetch filtered set of application resources.
	filter string should be in JSON format.eg: "vm_state:DOWN,name:[a-z]+"
	'''
	@classmethod
	def get_filtered(cls,service,filter_) :
		try:
			application_obj = application()
			option_ = options()
			option_._filter=filter_
			return application_obj.getfiltered(service, option_)
		except Exception as e :
			raise e

	'''
	* Use this API to count the application resources.
	'''
	@classmethod
	def count(cls,service) :
		try:
			application_obj = application()
			option_ = options()
			option_._count=True
			response = application_obj.get_resources(service, option_)
			if response :
				return response[0].__dict__['___count']
			return 0
		except Exception as e :
			raise e

	'''
	Use this API to count the filtered set of application resources.
	filter string should be in JSON format.eg: "vm_state:DOWN,name:[a-z]+"
	'''
	@classmethod
	def count_filtered(cls,service,filter_):
		try:
			application_obj = application()
			option_ = options()
			option_._count=True
			option_._filter=filter_
			response = application_obj.getfiltered(service, option_)
			if response :
				return response[0].__dict__['___count']
			return 0;
		except Exception as e :
			raise e

	'''
	Converts API response into object and returns the object array in case of get request.
	'''
	def get_nitro_response(self,service ,response):
		try :
			result=service.payload_formatter.string_to_resource(application_response, response, self.__class__.__name__)
			if(result.errorcode != 0) :
				if (result.errorcode == 444) :
					service.clear_session(self)
				if result.severity :
					if (result.severity == "ERROR") :
						raise nitro_exception(result.errorcode, str(result.message), str(result.severity))
				else :
					raise nitro_exception(result.errorcode, str(result.message), str(result.severity))
			return result.application
		except Exception as e :
			raise e


	'''
	Converts API response into object and returns the object array .
	'''
	def get_nitro_bulk_response(self,service ,response):
		try :
			result=service.payload_formatter.string_to_resource(application_responses, response, "application_response_array")
			if(result.errorcode != 0) :
				if (result.errorcode == 444) :
					service.clear_session(self)
				response = result.application_response_array
				i=0
				error = [application() for _ in range(len(response))]
				for obj in response :
					error[i]= obj._message
					i=i+1
				raise nitro_exception(result.errorcode, str(result.message), error)
			response = result.application_response_array
			i=0
			application_objs = [application() for _ in range(len(response))]
			for obj in response :
				if hasattr(obj,'_application'):
					for props in obj._application:
						result = service.payload_formatter.string_to_bulk_resource(application_response,self.__class__.__name__,props)
						application_objs[i] = result.application
						i=i+1
			return application_objs
		except Exception as e :
			raise e


	'''
	Performs generic data validation for the operation to be performed
	'''
	def validate(self,operationType):
		try:
			super(application,self).validate()
		except Exception as e :
			raise e

'''
Forms the proper response.
'''
class application_response(base_response):
	def __init__(self,length=1) :
		self.application= []
		self.errorcode = 0 
		self.message = "" 
		self.severity = "" 
		self.application= [ application() for _ in range(length)]
'''
Forms the proper response for bulk operation.
'''
class application_responses(base_response):
	def __init__(self,length=1) :
		self.application_response_array = []
		self.errorcode = 0 
		self.message = "" 
		self.application_response_array = [ application() for _ in range(length)]
